name: Software Testing Workflow

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      
      - name: Installing Dependencies
        run: npm install

      - name: Testing
        run: npm test
        continue-on-error: true

      - name: Coveralls Report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}